
---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r, echo=TRUE}
library(dplyr)
originaldata <- read.csv("activity.csv")
data <- filter(originaldata, !is.na(steps))
intervaldata <- group_by(data, interval)
intervaldata <- summarise(intervaldata, steps=mean(steps))
data <- group_by(data, date)
data <- summarise(data, steps=sum(steps))

```


## What is mean total number of steps taken per day?
```{r, echo=TRUE}
summary(data)
hist(as.matrix(data[,"steps"]), main="Histogram: Total number of steps per day", xlab = "Number of steps", col="red")
mean <- mean(as.matrix(data[,"steps"]))
median <- median(as.matrix(data[,"steps"]))
paste("The mean number of steps per day is", mean)
paste("The median number of steps per day is", median)
```


## What is the average daily activity pattern?
```{r, echo=TRUE}
summary(intervaldata)
plot(intervaldata, type="l", main="Average number of steps per interval")
maxdata <- filter(intervaldata, steps==max(steps))
paste("The interval with the max average number of steps is", maxdata["interval"])
```


## Imputing missing values
```{r, echo=TRUE}
missingcount = nrow(filter(originaldata, is.na(steps)))
paste("Number of missing values for step count is", missingcount)
paste("Using average for given interval to fill in missing data")
filledindata <- originaldata
for(i in unique(originaldata["interval"])){
    filledindata[filledindata["interval"]==i & is.na(filledindata["steps"]),"steps"] <- intervaldata[intervaldata["interval"]==i,"steps"]
}  
filledindata2 <- group_by(filledindata, date)
filledindata2 <- summarise(filledindata2, steps=sum(steps))
summary(filledindata2)
hist(as.matrix(filledindata2[,"steps"]), main="Histogram: Total number of steps per day", xlab = "Number of steps", col="blue")
mean <- mean(as.matrix(filledindata2[,"steps"]))
median <- median(as.matrix(filledindata2[,"steps"]))
paste("The mean number of infilled steps per day is", mean)
paste("The median number of infilled steps per day is", median)

```


## Are there differences in activity patterns between weekdays and weekends?
```{r, echo=TRUE, fig.height=10, fig.width=10}
filledindata$day <- weekdays(as.Date(filledindata$date))
filledindata$weekend <- (filledindata$day=="Sunday" | filledindata$day=="Saturday")
weekenddata <- filter(filledindata, weekend==TRUE)
weekdata  <- filter(filledindata, weekend==FALSE)
par(mfrow = c(2, 1), oma=c(1,1,1,1))
weekenddata <- group_by(weekenddata, interval)
weekenddata <- summarise(weekenddata, steps=mean(steps))
plot(weekenddata, type="l", main="Average number of steps per interval", xlab="Weekend")

weekdata <- group_by(weekdata, interval)
weekdata <- summarise(weekdata, steps=mean(steps))
plot(weekdata, type="l", xlab="Weekday")

```


